import React from "react";
import { FileText, AlertTriangle } from "lucide-react";
import { SUPPORT_EMAIL } from "@/components/layout/Footer";

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 text-left">
      <div className="space-y-3">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 text-xs font-bold uppercase tracking-wider">
          <FileText className="w-3.5 h-3.5" />
          <span>Terms of Use</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-white tracking-tight">
          Terms & Conditions
        </h1>
        <p className="text-xs text-slate-500 dark:text-slate-400">
          Last Updated: September 2026
        </p>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-3xl p-8 border border-slate-200 dark:border-slate-800 shadow-sm space-y-6 text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
        {/* Highlighted Disclaimer Box */}
        <div className="p-5 rounded-2xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900/50 space-y-2 text-amber-900 dark:text-amber-200">
          <div className="flex items-center gap-2 font-bold text-base">
            <AlertTriangle className="w-5 h-5 text-amber-600" />
            <span>Official Estimation Disclaimer</span>
          </div>
          <p className="text-xs sm:text-sm leading-relaxed">
            &quot;This is an estimate. Actual paint consumption and cost may vary depending on surface condition, application method, paint brand, coverage and local prices.&quot;
          </p>
        </div>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            1. Agreement to Terms
          </h2>
          <p>
            By accessing or using the Paint Calculator & Estimator website, you agree to be bound by these Terms & Conditions. If you do not agree to these terms, please do not use our calculation tools.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            2. Purpose of Calculations
          </h2>
          <p>
            The mathematical models, spreading rates (e.g. 10 m²/L), room area calculations, and cost summaries generated by our tools are provided for estimation, budgeting, and planning purposes only.
          </p>
          <p>
            Substrate porosity (raw unprimed drywall vs. smooth painted plaster), roller nap thickness, airless sprayer overspray, temperature, humidity, and individual manufacturer specs directly affect actual real-world paint usage. Users are encouraged to consult paint manufacturer technical data sheets before placing final material orders.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            3. Limitation of Liability
          </h2>
          <p>
            Under no circumstances shall Paint Calculator & Estimator or its developers be held liable for any direct, indirect, incidental, or consequential damages resulting from paint shortages, surplus paint purchases, labor cost disputes, contractor delays, or calculation errors.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 dark:text-white">
            4. Inquiries
          </h2>
          <p>
            Questions regarding our terms of service may be directed to:{" "}
            <code className="text-blue-600 dark:text-blue-400 font-bold">{SUPPORT_EMAIL}</code>.
          </p>
        </section>
      </div>
    </div>
  );
}
